# Generated by Django 2.0.6 on 2018-07-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appelation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('regionid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appelation',
                'managed': False,
            },
        ),
    ]
