# Generated by Django 2.0.6 on 2018-07-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'flavor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrapeFlavorProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('regionid', models.IntegerField(blank=True, null=True)),
                ('grapeid', models.IntegerField(blank=True, null=True)),
                ('dmnt_flavors', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grape_flavor_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('parent_regionid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'variety',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vineyard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('regionid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vineyard',
                'managed': False,
            },
        ),
    ]
